// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete.sql

package database

import (
	"context"
)

const deleteData = `-- name: DeleteData :exec
DELETE FROM users
`

func (q *Queries) DeleteData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteData)
	return err
}
